replicaCount: 2 

image:
  repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduprorepository
  tag: v3
  pullPolicy: Always

imagePullSecrets:
  - ecr-regcred 

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "" 

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  className: "" 

resources: {}

autoscaling:
  enabled: false 
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
