deployments:
  - name: app1
    replicaCount: 2
    namespace: prod
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduproproduction
      tag: v3
      pullPolicy: Always
    imagePullSecrets:
      - ecr-regcred
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    service:
      type: LoadBalancer
      port: 80
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

  - name: app2
    replicaCount: 3
    namespace: prod
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduproproduction
      tag: v3
      pullPolicy: Always
    imagePullSecrets:
      - ecr-regcred
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    service:
      type: LoadBalancer
      port: 81
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

  - name: app3
    replicaCount: 2
    namespace: prod
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduproproduction
      tag: v3
      pullPolicy: Always
    imagePullSecrets:
      - ecr-regcred
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    service:
      type: LoadBalancer
      port: 82
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

  - name: app4
    replicaCount: 2
    namespace: prod
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduproproduction
      tag: v3
      pullPolicy: Always
    imagePullSecrets:
      - ecr-regcred
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    service:
      type: LoadBalancer
      port: 83
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

  - name: app5
    replicaCount: 2
    namespace: prod
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduproproduction
      tag: v3
      pullPolicy: Always
    imagePullSecrets:
      - ecr-regcred
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    service:
      type: LoadBalancer
      port: 84
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
