deployments:
  - name: app1
    namespace: dev
    replicaCount: 2
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduprorepository
      tag: v2
      pullPolicy: Always
    service:
      type: NodePort
      port: 80
      nodePort: 30080
    resources: {}

  - name: app2
    namespace: dev
    replicaCount: 2
    image:
      repository: 545009833003.dkr.ecr.ap-northeast-2.amazonaws.com/eduprorepository
      tag: v2
      pullPolicy: Always
    service:
      type: NodePort
      port: 81
      nodePort: 30081
    resources: {}
