apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  strategy:
    type: {{ .Values.frontend.strategy.type | default "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable | default 1 }}
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default "fv1" }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.frontend.service.port | default 80 }}
