apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  annotations:
    metallb.universe.tf/address-pool: default-pool  # MetalLB에서 사용할 IP 풀 (필요에 따라 수정)
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
