{{- range .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .service.port }}
      nodePort: {{ .service.nodePort | default (add 30000 .service.port) }}
---
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: msa-loadbalancer
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - name: "http-80"
      protocol: TCP
      port: 80
      targetPort: 30080
    - name: "http-81"
      protocol: TCP
      port: 81
      targetPort: 30081
    - name: "http-82"
      protocol: TCP
      port: 82
      targetPort: 30082
    - name: "http-83"
      protocol: TCP
      port: 83
      targetPort: 30083
    - name: "http-84"
      protocol: TCP
      port: 84
      targetPort: 30084

