{{- range .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .service.port }}
---
{{- end }}

---
{{- range .Values.deployments }}
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  namespace: {{ .namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .ingress.ingressClassName | default "nginx" }}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: /index.php
            pathType: Exact
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
          - path: /login.php
            pathType: Exact
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
          - path: /logout.php
            pathType: Exact
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
          - path: /quiz.php
            pathType: Exact
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
---
{{- end }}
{{- end }}
