name: Build Image and Push to ECR (CI) & Deploy to ArgoCD (CD)

on: 
  push:
    branches: [main, dev]

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-var.outputs.IMAGE_TAG }}
      VALUES_FILE: ${{ steps.set-var.outputs.VALUES_FILE }}
      ECR_REPOSITORY: ${{ steps.set-var.outputs.ECR_REPOSITORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: ${{ secrets.ARN_ECR_PUSH_ROLE }}
          role-session-name: ecrPrivatePushRole

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Environment Variables
        id: set-var
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ECR_REPOSITORY=eduproproduction" >> $GITHUB_ENV
            echo "VALUES_FILE=values-prod.yaml" >> $GITHUB_ENV
            LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^prod-v[0-9]+$' | head -n 1)
            PREFIX="prod-v"
          else
            echo "ECR_REPOSITORY=eduprorepository" >> $GITHUB_ENV
            echo "VALUES_FILE=values.yaml" >> $GITHUB_ENV
            LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^dev-v[0-9]+$' | head -n 1)
            PREFIX="dev-v"
          fi

          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="${PREFIX}1"
          else
            TAG_NUMBER=$(echo $LATEST_TAG | sed "s/$PREFIX//")
            NEW_TAG="${PREFIX}$((TAG_NUMBER + 1))"
          fi

          echo "IMAGE_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "VALUES_FILE=$VALUES_FILE" >> $GITHUB_OUTPUT
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_OUTPUT
          echo "New image tag: $NEW_TAG"

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker Image to ECR
        id: push-image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update tag in values.yaml or values-prod.yaml
        run: |
          sed -i "s%tag: .*%tag: $IMAGE_TAG%" eduprorepository/$VALUES_FILE

      - name: Commit and Push Changes to values.yaml or values-prod.yaml
        run: |
          git config user.name "krtio"
          git config user.email "minwoo0612k@naver.com"
          git add eduprorepository/$VALUES_FILE
          git commit -m "Update image tag to $IMAGE_TAG" --author "krtio <minwoo0612k@naver.com>" --allow-empty
          git push origin ${{ github.ref_name }}

      - name: Create Git Tag for Versioning
        run: |
          git tag -a $IMAGE_TAG -m "Release $IMAGE_TAG"
          git push origin $IMAGE_TAG --force
