name: Build Image and Push to ECR (CI) & Deploy to ArgoCD (CD)

on:
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-var.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 Git 이력 가져오기 (태그 조회 가능)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: ${{ secrets.ARN_ECR_PUSH_ROLE }}
          role-session-name: ecrPrivatePushRole

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Environment Variables
        id: set-var
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=eduprorepository" >> $GITHUB_ENV
          
          # 최신 태그 가져오기
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+$' | head -n 1)

          # 태그가 없으면 v1, 있으면 숫자 증가
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="v1"
          else
            TAG_NUMBER=$(echo $LATEST_TAG | sed 's/v//')
            NEW_TAG="v$((TAG_NUMBER + 1))"
          fi

          echo "IMAGE_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "New image tag: $NEW_TAG"

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker Image to ECR
        id: push-image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update tag in values.yaml
        run: |
          sed -i "s%tag: .*%tag: $IMAGE_TAG%" eduprorepository/values.yaml

      - name: Commit and Push Changes to values.yaml
        run: |
          git config user.name "krtio"
          git config user.email "minwoo0612k@naver.com"
          git add eduprorepository/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG" --author "krtio <minwoo0612k@naver.com>" --allow-empty
          git push origin dev

      - name: Create Git Tag for Versioning
        run: |
          git tag -f $IMAGE_TAG
          git push origin $IMAGE_TAG --force
